-- MySQL Script generated by MySQL Workbench
-- 02/21/16 20:33:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facultyDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facultyDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facultyDb` DEFAULT CHARACTER SET utf8 ;
USE `facultyDb` ;

-- -----------------------------------------------------
-- Table `facultyDb`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facultyDb`.`department` ;

CREATE TABLE IF NOT EXISTS `facultyDb`.`department` (
  `departmentId` INT NOT NULL,
  `departmentName` VARCHAR(250) NOT NULL,
  `departmentAbbr` VARCHAR(10) NULL,
  PRIMARY KEY (`departmentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facultyDb`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facultyDb`.`Admin` ;

CREATE TABLE IF NOT EXISTS `facultyDb`.`Admin` (
  `adminId` INT NOT NULL,
  `fName` VARCHAR(50) NULL,
  `lName` VARCHAR(50) NULL,
  `username` VARCHAR(256) NULL,
  `password` VARCHAR(256) NULL,
  `salt` CHAR(6) NULL,
  `accessLevel` INT NULL,
  `departmentId` INT NOT NULL,
  PRIMARY KEY (`adminId`),
  INDEX `fk_Admin_department_idx` (`departmentId` ASC),
  CONSTRAINT `fk_Admin_department`
    FOREIGN KEY (`departmentId`)
    REFERENCES `facultyDb`.`department` (`departmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facultyDb`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facultyDb`.`room` ;

CREATE TABLE IF NOT EXISTS `facultyDb`.`room` (
  `roomNumber` INT NOT NULL,
  `roomMap` VARCHAR(50) NULL,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`roomNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facultyDb`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facultyDb`.`Employees` ;

CREATE TABLE IF NOT EXISTS `facultyDb`.`Employees` (
  `facultyId` INT NOT NULL,
  `fName` VARCHAR(50) NULL,
  `lName` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  `officeHours` VARCHAR(250) NULL,
  `isActive` TINYINT(1) NULL,
  `isFaculty` TINYINT(1) NULL,
  `phone` CHAR(14) NULL,
  `about` VARCHAR(500) NULL,
  `education` VARCHAR(500) NULL,
  `highlights` VARCHAR(500) NULL,
  `departmentId` INT NOT NULL,
  `roomNumber` INT NOT NULL,
  PRIMARY KEY (`facultyId`),
  INDEX `fk_Employees_department1_idx` (`departmentId` ASC),
  INDEX `fk_Employees_room1_idx` (`roomNumber` ASC),
  CONSTRAINT `fk_Employees_department1`
    FOREIGN KEY (`departmentId`)
    REFERENCES `facultyDb`.`department` (`departmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_room1`
    FOREIGN KEY (`roomNumber`)
    REFERENCES `facultyDb`.`room` (`roomNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
